# Generated by Django 5.1.6 on 2025-02-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('house_type', models.CharField(choices=[('Bedsitter', 'Bedsitter'), ('Single Room', 'Single Room'), ('One Bedroom', 'One Bedroom'), ('Two Bedroom', 'Two Bedroom')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('apartment_name', models.CharField(max_length=255)),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
